import jwt from 'jsonwebtoken';
import fs from 'fs';
import db from '../database';
import cloudinary from '../config/cloudinaryConfig';
import Gif from '../models/gif';


exports.createGif = (req, res) => {

  console.log('** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **');

  const { file } = req;
  // File Upload
  cloudinary.uploader.upload(file, { tags: req.title }, (error, result) => {

    console.log();
    console.log('** File Upload');
    if (error) {
      console.warn(error);
    }
    console.log('* public_id for the uploaded image is generated by Cloudinary\'s service.');
    console.log('* ', result.public_id);
    console.log('* ', result.url);

    const gif = new Gif();
    gif.ownerId = '';
    gif.title = result.original_filename;
    gif.comment = '';
    gif.authorName = '';
    gif.imageUrl = result.url;

    // Save Image To DB
    db('gifs')
      .returning('*')
      .insert(gif).then((data) => {
        console.log(data);
        res.status(201).json({
          status: 'success',
          data: {
            gifId: result.public_id,
            message: 'GIF image successfully posted',
            createdOn: result.created_at,
            title: result.original_filename,
            imageUrl: result.url,
          },
        });
      })
      .catch(
        (err) => {
          res.status(500).json({
            status: 'error',
            error: err.detail,
          });
        },
      );
  });

  // let filename = req.files.dataFile.path;
  // cloudinary.uploader.upload(filename, {
  //   tags: 'gotemps',
  //   resource_type: 'auto',
  // })
  //   .then(function (file) {
  //     console.log('Public id of the file is  ' + file.public_id);
  //     console.log('Url of the file is  ' + file.url);
  //     template.dataFile = file.url;
  //   })
  //   .catch(function (err) {
  //     if (err) {
  //       console.warn(err);
  //     }
  //   });
};
